name: cat_summon_circle_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  google_fonts: ^2.2.0
  flutter_native_splash: ^2.0.1+1
  cupertino_icons: ^1.0.2

flutter_native_splash:
  color: "#ffffcc"
  image: "assets/splash.png"
  android: true
  ios: true
  web: true

dev_dependencies:

flutter:

  uses-material-design: true

  assets:
    - assets/

